### ISSUE TITLE
TableUtils cannot render as TSV, only CSV

### ISSUE THREAD

**Issue by prothSFDC** [paulroth3d/jupyter-ijavascript-utils#44]
CSV works great for working with larger datasets
but sometimes we want to capture tinier ones
and many spreadsheets explicitly know TSV and not CSV when copying and pasting.

**Comment by paulroth3d** [comment]
completed in version 1.31
https://jupyter-ijavascript-utils.onrender.com/TableGenerator.html#renderCSV
